### ISSUE TITLE
F: Definição das aplicações previstas para validar a proposta de solução

### ISSUE THREAD

**Issue by altjohndev** [fga-verival/2017-1Grupo1#6]
- [x] Definir tópicos avaliados
- [x] Definir funcionalidades acompanhadas
- [x] Definir extensões possíveis
- [ ] Propor processo de aplicação

**Comment by pwener** [comment]
[Definir tópicos avaliados](https://github.com/fga-verival/2017-1Grupo1/wiki/T%C3%B3picos-das-funcionalidades-avaliadas)

**Comment by rafaelrabetti** [comment]
[Definir Funcionalidades](https://github.com/fga-verival/2017-1Grupo1/wiki/Definir-Funcionalidades)
